diagram:
  color:
    colormap: OrRd
    divisions: 7
  text:
    font-size: 10
  coordinate-system:
    x:
      value: 2
      unit: pt
    y:
      value: 32
      unit: ex
    scale: 2

canvas:
  width: 50
  height: 100
